[workspace]
resolver = "2"
members = [
    "packages/srctrait-note",
    "packages/srctrait-note-cli",
]

[workspace.dependencies]
srctrait-common-testing = "4"
srctrait-common-chronox = "1"
srctrait-common-clapx = "1"
srctrait-common-tomlx = "3"
srctrait-note = { version="2", path = "packages/srctrait-note" }
